global using AutoMapper;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using SocialMedia.Core.DTOs.Comments;
global using SocialMedia.Core.DTOs.Posts;
global using SocialMedia.Core.DTOs.Users;
global using SocialMedia.Core.Entities;
global using SocialMedia.Core.Interfaces.Comment;
global using SocialMedia.Core.Interfaces.Post;
global using SocialMedia.Core.Interfaces.UnitOfWork;
global using SocialMedia.Core.Interfaces.User;
global using SocialMedia.Infrastructure.Data;
global using SocialMedia.Infrastructure.Data.Configurations;
global using SocialMedia.Infrastructure.Repositories.Comments;
global using SocialMedia.Infrastructure.Repositories.Posts;
global using SocialMedia.Infrastructure.Repositories.Users;

